version: "3"
services: 
    db:
        image: postgres
        container_name: postgres
        volumes:
            - ./db-data:/var/lib/postgresql/data
            - ./docker/init_db:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=todo_db
        ports:
            - "5432:5432"

    web:
        container_name: todo_server
        depends_on:
            - db
        ports:
            - 8080:8080
        tty: true
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        environment:
            - GOPATH=/go
        volumes:
            - ./go:/go

volumes:
    db-data: # ローカルのディレクトリにデータを保存